# Deployment of Azure Keyvaults
jobs:
  - job: deploy_kv
    dependsOn: deploy_resource_groups
    displayName: 'Deploy Keyvaults'
    steps:

    # Deploy KV
    - ${{ each value in parameters.kvNamesAndRGs }}:
      - task: AzureCLI@2
        enabled: true
        displayName: 'Create Key Vault [${{ value }}]'
        inputs:
          azureSubscription: "${{ parameters.serviceConnection }}"
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          'inlineScript': |

            kvName=$(echo ${{ value }} | awk -F ":" '{print $1}')
            kvResourceGroupName=$(echo ${{ value }} | awk -F ":" '{print $2}')

            kvPurge=(az keyvault purge \
            --name "$kvName" \
            --location ${{ parameters.azLoc }}) 

            az deployment group create \
            --template-file "templates/bicep/keyvault.bicep" \
            --name "deploy-kv-$kvName-$RANDOM" \
            --resource-group "$kvResourceGroupName" \
            --parameters \
              kvName="$kvName" \
              tenantId="${{ parameters.azTenantId }}" \
              kvAccessPolicies='${{ parameters.kvAccessPolicies }}' \
              kvIpRules='${{ parameters.kvIpRules }}' \
              kvVirtualNetworkRules='${{ parameters.kvVirtualNetworkRules }}' \
              azLoc="${{ parameters.azLoc }}" \
              kvTagName="$kvName" \
              kvTagEnvName="${{ parameters.env }}" \
              kvTagDeployedBy="${{ parameters.deployedBy }}" \
            --output none && \
            echo "Deployed Key Vault [$kvName] to Resource Group [$kvResourceGroupName]." || exit 2