# Deployment of Azure Storage Account
jobs:
  - job: deploy_storage
    dependsOn: deploy_resource_groups
    displayName: 'Deploy Storage Account'
    steps:

    # Deploy Storage Account
    - task: AzureCLI@2
      enabled: true
      displayName: 'Deploy Storage Account to [${{ parameters.strRgName }}]'
      inputs:
        azureSubscription: "${{ parameters.serviceConnection }}"
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        'inlineScript': |

           storageAccountName=$(echo "${{ parameters.strRgName }}" | tr -d '-' | sed 's/rg/str/g')

           az deployment group create \
           --name "deploy-$storageAccountName-$RANDOM" \
           --resource-group "${{ parameters.strRgName }}" \
           --template-file "templates/bicep/storageAccount.bicep" \
           --parameters \
             strName="$storageAccountName" \
             strFileShareName="${{ parameters.strFileShareName }}" \
             strSku="${{ parameters.strSku }}" \
             strKind="${{ parameters.strKind }}" \
             strAccessTier="${{ parameters.strAccessTier }}" \
             strSupportHttpsTrafficOnly="${{ parameters.strSupportHttpsTrafficOnly }}" \
             strMinimumTlsVersion="${{ parameters.strMinimumTlsVersion }}" \
             azLoc="${{ parameters.azLoc }}" \
             strTagName="$storageAccountName" \
             strTagEnvName="${{ parameters.env }}" \
             strTagDeployedBy="${{ parameters.deployedBy }}" \
           --output none && \
           echo "Deployed [$storageAccountName] successfully."