# Deployment of Azure Resource Groups using Bicep.
jobs:
  - job: deploy_resource_groups
    displayName: 'Deploy Resource Groups'
    steps:

    # Deploy Resource Groups.
    - ${{ each rgName in parameters.rgNames }}:
      - task: AzureCLI@2
        enabled: true
        displayName: 'Create RG [${{ rgName }}]'
        inputs:
          azureSubscription: "${{ parameters.serviceConnection }}"
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          'inlineScript': |
            
            checkExistingResourceGroup=$(az group list \
            --query "[?name=='${{ rgName }}'].name" \
            --output tsv)

            if [[ "$checkExistingResourceGroup" == "${{ rgName }}" ]]; then
                echo "Found Resource Group [${{ rgName }}]." || exit 2
            else

                az deployment sub create \
                -f "templates/bicep/resourceGroup.bicep" \
                --name "deploy-rg-${{ rgName }}-$RANDOM" \
                --location "${{ parameters.azLoc }}" \
                --parameters \
                  rgName="${{ rgName }}" \
                  azLoc="${{ parameters.azLoc }}" \
                  rgTagName="${{ rgName }}" \
                  rgTagEnvName="${{ parameters.env }}" \
                  rgTagDeployedBy="${{ parameters.deployedBy }}" \
                --output none && \
                echo "Deployed [${{ rgName }}] successfully." 
            fi